apiVersion: apps/v1
kind: Deployment
metadata:
  name: student8-deployment
  namespace: student8
spec:
  selector:
    matchLabels:
      app: student8
  template:
    metadata:
      labels:
        app: student8
    spec:
      containers:
      - name: studentx
        image: registry.tanzu.dk/ops2devops/student8:v1
