apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: student8
spec:
  selector:
    matchLabels:
      app: student8
  template:
    metadata:
      labels:
        app: student8
    spec:
      containers:
      - name: student8
        image: registry.tanzu.dk/ops2devops/student8:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student8
spec:
  type: NodePort
  selector:
    app: student8
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30018 # Remember to change to student number.

